import { Page, Text } from "@/components";
import Head from "next/head";
import { Column, EmailBox, MainGrid } from "./styles";
import { useTheme } from "styled-components";
import Image from "next/image";
import creditCards from "../assets/creditCards.png";
import { CheckoutForm } from "./components/CheckoutForm";
import { RadioGroup } from "./components/RadioGroup";

export default function Home() {
  const { spacing } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page canGoBack>
        <MainGrid>
          <Column>
            <div>
              <Text
                preset="h4"
                as="h1"
                color="title"
                style={{ paddingBottom: spacing.s10 }}
              >
                Estamos quase lá!
              </Text>

              <Text
                as="h2"
                color="title"
                style={{ paddingBottom: spacing.s32 }}
              >
                Insira seus dados de pagamento abaixo:
              </Text>
            </div>

            <Image
              alt="credit-cards-image"
              src={creditCards}
              width={215}
              height={50}
              style={{ paddingBottom: spacing.s32, height: 50, width: 215 }}
            />

            <CheckoutForm />
          </Column>

          <Column>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <Text
                preset="h4"
                as="h1"
                color="title"
                style={{ paddingBottom: spacing.s10 }}
              >
                Confira o seu plano:
              </Text>

              <EmailBox>
                <Text as="span" color="title" preset="footnote">
                  fulano@cicrano.com.br
                </Text>
              </EmailBox>
            </div>

            <RadioGroup />
          </Column>
        </MainGrid>
      </Page>
    </>
  );
}
