import { Page, Text } from "@/components";
import Head from "next/head";
import { Column, MainGrid } from "./styles";
import { useTheme } from "styled-components";
import Image from "next/image";
import creditCards from "../assets/creditCards.png";
import { CheckoutForm } from "./components/CheckoutForm";

import { Offers } from "./components/Offers";

export default function Home() {
  const { spacing } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <MainGrid>
          <Column>
            <div style={{ alignSelf: "baseline" }}>
              <Text
                preset="h4"
                as="h1"
                color="title"
                style={{ paddingBottom: spacing.s10 }}
              >
                Estamos quase lá!
              </Text>

              <Text
                as="h2"
                color="title"
                style={{ paddingBottom: spacing.s32 }}
              >
                Insira seus dados de pagamento abaixo:
              </Text>
            </div>

            <Image
              alt="credit-cards-image"
              src={creditCards}
              width={215}
              height={50}
              style={{ paddingBottom: spacing.s32, height: 70, width: 215 }}
            />

            <CheckoutForm />
          </Column>

          <Offers />
        </MainGrid>
      </Page>
    </>
  );
}
